
#创建user表
#DROP TABLE IF EXISTS USER;
CREATE TABLE IF NOT EXISTS `user`(
	`uid` INT PRIMARY KEY AUTO_INCREMENT,
	`account` VARCHAR(20) UNIQUE NOT NULL,
	`password` VARCHAR(20) NOT NULL
);

#创建player表
#DROP TABLE IF EXISTS `player`;
CREATE TABLE IF NOT EXISTS `player`(
	`pid` INT PRIMARY KEY AUTO_INCREMENT,
	`account` VARCHAR(20)  NOT NULL,
	`name` VARCHAR(20) UNIQUE NOT NULL,
	`head` INT NOT NULL,
	`score` INT NOT NULL
);
